import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { connection } from "next/server";
import { Suspense } from "react";
import { baloo2 } from "@/public/fonts/baloo-2";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

async function UTSSR() {
   await connection();
   return <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />;
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body className={`${baloo2.className} antialiased`}>
            <Suspense>
               <UTSSR />
            </Suspense>
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               {children}
               <Toaster position="top-right" />
            </ThemeProvider>
         </body>
      </html>
   );
}
