import type { Metadata } from "next";
import "./globals.css";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "../api/uploadthing/core";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { connection } from "next/server";
import { Suspense } from "react";
import { baloo2 } from "@/public/fonts/baloo-2";
import { hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { Providers } from "@/components/providers/providers";
import { setRequestLocale } from "next-intl/server";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

async function UTSSR() {
   await connection();
   return <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />;
}

export default async function RootLayout({
   children,
   params,
}: Readonly<{
   children: React.ReactNode;
   params: Readonly<{
      locale: string;
   }>;
}>) {
   const { locale } = await params;
   if (!hasLocale(routing.locales, locale)) {
      notFound();
   }

   console.log(locale);

   setRequestLocale(locale);

   return (
      <html suppressHydrationWarning lang={locale}>
         <body
            suppressHydrationWarning
            className={`${baloo2.className} antialiased`}
         >
            <Suspense>
               <UTSSR />
            </Suspense>
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
